\documentclass{beamer}
\usetheme{metropolis}
\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\usepackage{epstopdf}
\usepackage{colortbl, xcolor}


\title{signalHsmm: prediction of malarial signal peptides}
\date{}
\author{Micha\l{} Burdukiewicz\inst{1}*, Piotr Sobczyk\inst{2}, Pawe\l{} B\l{}a\.{z}ej\inst{1}, Pawe\l{} Mackiewicz\inst{1}}
\institute{\textsuperscript{1}University of Wroc\l{}aw, Department of Genomics, 

\textsuperscript{2}Wroc\l{}aw University of Science and Technology, Faculty of Pure and Applied Mathematics,
}

\begin{document}
  \maketitle
  \section{Signal peptides}
  
\begin{frame}{}
<<knitrIntro, echo = FALSE, message=FALSE,warning=FALSE>>=
source("my_ggplot_theme.R")

g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

library(dplyr)
library(reshape2)
library(xtable)
library(biogram)

load("./dat/signalhsmm_poster.RData")

@

\end{frame}

  
  \begin{frame}{}

  \begin{figure}
\includegraphics[width=0.9\textwidth]{static_figure/SP.png}
\end{figure}
      \begin{itemize}
        \item n-region: mostly basic residues~\citep{nielsen_prediction_1998},
        \item h-region: strongly hydrophobic residues~\citep{nielsen_prediction_1998},
        \item c-region: a few polar, uncharged residues~\citep{jain_signal_1994}.
      \end{itemize}
\end{frame}

\begin{frame}
\begin{table}[ht]
\centering
\begin{tabular}{ll}
  \toprule
Group & Amino acids \\ 
  \midrule
1 & D, E, H, K, N, Q, R \\ 
   \rowcolor[gray]{0.85}2 & G, P, S, T, Y \\ 
  3 & F, I, L, M, V, W \\ 
   \rowcolor[gray]{0.85} 4 & A, C \\ 
   \bottomrule
\end{tabular}
\end{table}
\end{frame}


\begin{frame}
<<echo = FALSE,message=FALSE,results='asis',fig.width=14, fig.height=9>>=
freq_nondeg <- read.csv2("./dat/freq_nondeg.csv")[, -1]
freq_deg <- read.csv2("./dat/freq_deg.csv")[, -1]

do_pca <- function(x) 
  x %>% 
  select(-type, -taxon) %>% 
  prcomp(center = TRUE, scale = TRUE) %>% 
  getElement("x") %>% 
  data.frame() %>% 
  select(1, 2) %>% 
  cbind(select(x, type, taxon), .) %>% 
  mutate(type_nice = factor(type, labels = c("Mature peptide", "Signal peptide")),
         taxon_nice = factor(taxon, labels = c("other", "Plasmodium"))) %>% 
  mutate(both = paste0(type_nice, "\n(", taxon_nice, ")\n"))

dat_deg <- do_pca(freq_deg) 
dat_nondeg <- do_pca(freq_nondeg)

# dat_deg <- read.table("PCAgr.txt", header = TRUE, sep = "\t")
# dat_nondeg <- read.table("PCA.txt", header = TRUE, sep = "\t")
# colnames(dat_deg) <- c("both", "PC1", "PC2")
# colnames(dat_nondeg) <- c("both", "PC1", "PC2")

plot_pca <- function(x)
  ggplot(x, aes(x = PC1, y = PC2, fill = both)) + 
  geom_density_2d(color = "black", contour = TRUE) +
  #geom_point() +
  stat_density2d(aes(fill=both,alpha=..level..), color = "black", contour = TRUE, geom="polygon") +
  scale_linetype_discrete("") +
  scale_fill_discrete("") +
  scale_shape_discrete("") +
  scale_color_discrete("") +
  scale_x_continuous("Principal Component 1\n") +
  scale_y_continuous("Principal Component 2") +
  scale_alpha_continuous(range = c(0.25, 0.4)) +
  guides(alpha = FALSE) +
  my_theme

p1 <- plot_pca(dat_nondeg) + ggtitle("Full alphabet") 
p2 <- plot_pca(dat_deg) + ggtitle("Reduced alphabet") + guides(fill = FALSE)
leg <- g_legend(p1)

print(p1)
@ 

\end{frame}

\begin{frame}
<<echo = FALSE,message=FALSE,results='asis',fig.width=14, fig.height=9>>=
print(p2)
@ 
\end{frame}



\begin{frame}
<<echo = FALSE,message=FALSE,results='asis',fig.width=14, fig.height=9>>=
grid.arrange(p1 + guides(fill = FALSE), p2 + guides(fill = FALSE), 
             leg, nrow = 3, heights = c(0.47, 0.47, 0.06))

@ 


\end{frame}


\begin{frame}

Countour plot of first two components in Pricincipal Compoment Analysis of amino acid frequency. The signal peptides from malaria and other taxons differ significantly when the full amino acid alphabet is employed. After the reduction of the alphabet, the signal peptides group together despite their origin.

\end{frame}

\begin{frame}{Acknowledgements and funding}

This research was partially funded by the KNOW Consortium and National Science Center (2015/17/N/NZ2/01845).

\small{
\begin{itemize}
\item Paweł Mackiewicz.
\item \textbf{biogram} package (\url{https://cran.r-project.org/package=biogram}):
\begin{itemize}
\small
\item Piotr Sobczyk,
\item Chris Lauber.
\end{itemize}
\end{itemize}
}

\end{frame}



\begin{frame}[allowframebreaks]
        \frametitle{References}
  \bibliographystyle{apalike}
  \bibliography{signalhsmm_poster}
\end{frame}


\end{document}